# This file was generated by GoReleaser. DO NOT EDIT.
cask "bsfw" do
  name "bsfw"
  desc "Bytesafe Firewall CLI — inspect firewalls, query logs, manage config as code"
  homepage "https://github.com/bytesafedev/bsfw"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bsfw"
  manpage "man/bsfw.1"
  bash_completion "completions/bsfw.bash"
  zsh_completion "completions/bsfw.zsh"
  fish_completion "completions/bsfw.fish"

  on_macos do
    on_intel do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "dbab89f6f4b974f93e05afb9970f8a8601d0b156f4cf0075b98d57459a03cb58"
    end
    on_arm do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "3b48db2ca22bec74097ba30b474d579276f7f1f4e81fbaaff8aafd904755ff67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "fc6de3480ca06c4aeb28390afcbed7f7de5e2abf35274418548f9afe8d10fa5b"
    end
    on_arm do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "bb651310765c7035cec0d67448b7dad58a700aacab97c2941ef773ae51eb0de2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bsfw"]
    end
  end

  # No zap stanza required
end
