# This file was generated by GoReleaser. DO NOT EDIT.
cask "bsfw" do
  name "bsfw"
  desc "Bytesafe Firewall CLI — inspect firewalls, query logs, manage config as code"
  homepage "https://github.com/bytesafedev/bsfw"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bsfw"
  manpage "man/bsfw.1"
  bash_completion "completions/bsfw.bash"
  zsh_completion "completions/bsfw.zsh"
  fish_completion "completions/bsfw.fish"

  on_macos do
    on_intel do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "65b0eb2c53088b45e296692e444c2e91413e1af4bcb595f6e241ab77ca9a23c6"
    end
    on_arm do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "c7bf536743c68c7c561bbe4b276326a79e8e6d05eaa776f7be696ea86c0c56ea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "98ceffb3bf71cba636010629dae1f11b700a7c6755ce5a5191ce82920ac99dc7"
    end
    on_arm do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "0459599fb2c7cbcf956619971a12ae2f7c642d125554f3d211ad68e820c69bb7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bsfw"]
    end
  end

  # No zap stanza required
end
