# This file was generated by GoReleaser. DO NOT EDIT.
cask "bsfw" do
  name "bsfw"
  desc "Bytesafe Firewall CLI — inspect firewalls, query logs, manage config as code"
  homepage "https://github.com/bytesafedev/bsfw"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bsfw"
  manpage "man/bsfw.1"
  bash_completion "completions/bsfw.bash"
  zsh_completion "completions/bsfw.zsh"
  fish_completion "completions/bsfw.fish"

  on_macos do
    on_intel do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "c5fe8f8e93e44d4209059c8ac61f2a07f13b8bc11daa4b80d6347fe5e0bfadbc"
    end
    on_arm do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "ba08757ae1831061e1c1e6c423fffe7007685352d50e020f245ec40a7a840e38"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "53d218f51f9192420187a17482e0ad04e262110b6d0503307da12cb141569bdc"
    end
    on_arm do
      url "https://github.com/bytesafedev/bsfw/releases/download/v#{version}/bsfw_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bytesafedev/bsfw"
      sha256 "2fc7d2012fc85af27bbd54e1fbb3bc8ad97474df893e56a0054838b09da1c7af"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bsfw"]
    end
  end

  # No zap stanza required
end
